name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout workflow templates repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          repository: reinrom/workflow.tamplates@main
          token: ${{ secrets.WORKFLOW_REPO_TOKEN }}
          path: workflow-templates

      - name: Call external workflow
        run: |
          cp -r workflow-templates/.github/workflows ./workflows

  # Service Job --------------------------------------------------------------------------
  #service:
  #  strategy:
  #      fail-fast: false
  #      matrix:
  #        role: [element]
  #        build_type: [Release]
  #        #runner: [wjr-self-wslubuntu64]
  #        runner: [ubuntu-latest]
  #  #uses: ./.github/workflows/service.yml
  #  uses: reinrom/workflow.tamplates/.github/workflows/service.yml@main
  #  with:
  #    role: ${{ matrix.role }}
  #    build_type: ${{ matrix.build_type }}
  #    runner: ${{ matrix.runner }}
  #  secrets:
  #    token_sonar: ${{ secrets.SONAR_TOKEN }}
  #    token_github: ${{ secrets.GITHUB_TOKEN }}
  #    token_ci: ${{ secrets.CI_TOKEN_TMP }}
  #    token: ${{ secrets.WORKFLOW_REPO_TOKEN }}
